### ISSUE TITLE
Changing @boot subvolume to @grub subvolume

### ISSUE THREAD

**Issue by tommytran732** [classy-giraffe/easy-arch#11]
Now that I think about it, the only thing that we want to be persistent in /boot (apart from the ESP partition) is /boot/grub. 

It might be a better idea to have a @grub subvolume for that, and let the initramfs as well as the kernel be part of the @ subvolume. If an update breaks the kernel, we still would be able to boot into the old snapshot. What do you think?

**Comment by classy-giraffe** [comment]
I guess I'll switch to LUKS 2 leaving boot unencrypted.
