### ISSUE TITLE
[feature]: Adding more package options to script.

### ISSUE THREAD

**Issue by iSparsh** [classy-giraffe/easy-arch#13]
Hello there, great work!
Reading through the script I had a few suggestions:-
1. In the base installation command, I notice `base-devel` is missing. It already includes a bunch of stuff like sudo, gawk, gcc, automake and others. I realize that some users may not want all of the things so we should definitely keep a condition (like the kernel choices but only yes/no for this one) whether the user wants to install this package or not.
2. Similarly, we should keep a condition for users to have a choice between their network utilities (example: NetworkManager, iwd, or skip/install later).

I would definitely like to add them myself as soon as I can, but real-life is keeping me busy atm.

**Comment by classy-giraffe** [comment]
I added a section where you can pick up a way to handle networking.

**Comment by iSparsh** [comment]
Thanks for the prompt changes! Love the script. Just had a question, would you accept a PR where base-devel gets installed (hard-coded) ? Or should I make a section where the user can choose to install the package optionally?
I'm highly in favor of this package because it takes care of all dependencies to make an compile user repos, git clone and all others. Currently, nothing of that sort is being installed on the system.

**Comment by iSparsh** [comment]
I have made a PR regarding the base devel package so i'll close this issue
