### ISSUE TITLE
Consider switching to encrypted swap or zram

### ISSUE THREAD

**Issue by tommytran732** [classy-giraffe/easy-arch#2]
I don't think the way it sets up unencrypted swap right now is a good idea. I think its better to encrypt it using dmcrypt or just to switch to zram and use the same configuration as Fedora does.

**Comment by classy-giraffe** [comment]
All right, looking to implement it. :D

**Comment by wbob** [comment]
added a btrfs swapfile the other day, for a suggestion:

```
# optional: retroactively add a swap subvolume on an existing btrfs disk
mkdir -p /mnt/btrfs
mount /dev/mapper/cryptroot  /mnt/btrfs
cd /mnt/btrfs
btrfs subvol create @swap

mkdir -p /swap

# /etc/fstab
/dev/mapper/cryptroot /swap   btrfs   subvol=@swap,noatime,compress=no,nodatasum,nodatacow 0 0

# man 5 btrfs
truncate -s 0 file
chattr +C file
# man mkswap
dd if=/dev/zero of=file bs=1MiB count=$((8*1024))
chmod 0600 file
mkswap file
swapon file

# /etc/fstab
/swap/file        none    swap    sw 0 0
```

**Comment by classy-giraffe** [comment]
@iSparsh I'm in favor of ZRAM as well, currently I'm reading about how to implement it. Looks like there's a systemd unit for that but AUR has a package for it too.

**Comment by iSparsh** [comment]
I'm not sure how helpful this is (and you'll have to watch the full video i'm linking) but this has implementation of Zram. You can take a look at [this](https://youtu.be/dohxv1ULcL4) _at 24:00 minute mark roughly_

**Comment by iSparsh** [comment]
@classy-giraffe any updates on this? I have also opened a PR regarding the packages so that is pending as well.

**Comment by iSparsh** [comment]
Ok from some research i've found that zram-generator from the official repositories is the way to go. However, the script would need to leave a note (post-install) telling the user to adjust the values of zram in the config file. Is that okay @classy-giraffe

**Comment by tommytran732** [comment]
Done in https://github.com/classy-giraffe/easy-arch/pull/19

**Comment by tommytran732** [comment]
And nope, we don't need systemd-zram-generator :P 

That package is nice and all, but we don't need it. I just followed the Arch wiki for this instead ;)

**Comment by tommytran732** [comment]
Okay the PR is merged so I am closing this
