### ISSUE TITLE
Adding normal user account

### ISSUE THREAD

**Issue by fawzakin** [classy-giraffe/easy-arch#22]
Hello, I'm curious why the script doesn't ask for a normal user and only leaves root as the initial user.

My extensive fork [here](https://gitlab.com/fawzakin/easy-arch) has that feature. I wonder if it is a good idea if I create a pull request for that.

Thank you for your script.

**Comment by classy-giraffe** [comment]
Cause i was lazy to figure out a way to use sed and modify the sudoers file to add the said user to wheel 😂 but sure if you make a pull request I'll check it!

**Comment by classy-giraffe** [comment]
Actually your fork is cool but it's like an entire new script (and you seem to know bash way better than I do, on a sidenote i literally wrote this script half assed and lazy).
