### ISSUE TITLE
Adjustments to default mount settings

### ISSUE THREAD

**Issue by pm4rcin** [classy-giraffe/easy-arch#26]
Hi, I think that default mount options should be revisited. I don't think we need "ssd" since btrfs can automatically detect disk type. Another option "autodefrag" in my opinion should be avoided since defragmentation reduces lifespan of SSDs. And for the space_cache I think it should be renamed to space_cache=v2 discussion: [1](https://pagure.io/fedora-btrfs/project/issue/24), [2](https://github.com/kdave/btrfs-progs/issues/295)
https://github.com/classy-giraffe/easy-arch/blob/80ffc96f99857e620262012f03decde6fcf709a2/easy-arch.sh#L135-L137
If you think I'm wrong on any options make sure to correct me. :)

**Comment by classy-giraffe** [comment]
Done! Thanks (check the code now).
