### ISSUE TITLE
Problem with snapshots subvolume

### ISSUE THREAD

**Issue by pm4rcin** [classy-giraffe/easy-arch#27]
Hi, I saw that you first create the subvolume .snapshots, mount it and later on you create the snapper config and delete the subvolume and create a directory .snapshots and mount that directory. Are this correct steps for setting up snapper or did you write too many lines? I'm asking seriously since it's new to me so I could not be familiar with the steps.

**Comment by classy-giraffe** [comment]
Yes it works like that, that step is needed in order to make snapper work (it will take care of recreating the subvolume).

**Comment by pm4rcin** [comment]
Oh so basically after you create the subvolume it is mounted and written to fstab. And then you delete it so snapper could recreate it and you mount all subvolumes again because they are on fstab.
Another question since you create snapper config with ```--no-dbus```. What's the reason for that option if you could explain?

**Comment by classy-giraffe** [comment]
Essentially because we're working in a chroot environment, check [this issue](https://github.com/wesbarnett/snap-pac/issues/23). If you were in a booted environment, you wouldn't need to add `--no-dbus` flag.
