### ISSUE TITLE
Proposition: two hard drive setup & systemd boot

### ISSUE THREAD

**Issue by Cyfraka** [classy-giraffe/easy-arch#28]
First I want to say that easy-arch is the perfect script for my laptop.

Propositions I will be happy to see and test if you implement one ore both of them:

1) I have a 256GB SSD and 128 GB M.2 SSD and for the moment BTRFS using the both of the drives I used only in Fedora 34/35
2) Systemd boot

**Comment by classy-giraffe** [comment]
To the first question my answer is "I can think about it". Regarding the second question, that's a no for two reasons:
1) Systemd boot is nowhere near as featureful as GRUB (can we even consider it as a bootloader? cause it just launches EFI files).
2) It doesn't allow booting from snapshots. :D

**Comment by Cyfraka** [comment]
Thanks for accepting the idea about the 2 disks and agree that without snapshots it's worthless to change GRUB for anything else. Time for Coffee :)

**Comment by pm4rcin** [comment]
> To the first question my answer is "I can think about it". Regarding the second question, that's a no for two reasons:
> 
>     1. Systemd boot is nowhere near as featureful as GRUB (can we even consider it as a bootloader? cause it just launches EFI files).
> 
>     2. It doesn't allow booting from snapshots. :D

Ad. 1 Yes systemd-boot is UEFI boot manager not bootloader but who really cares. The pros are simple configuration that is enough for many users.
Ad. 2 That's what I thought too but surprise: [snapper-systemd-boot.sh](https://github.com/lepz0r/snapper-systemd-boot.sh) ;)

**Comment by Cyfraka** [comment]
Related to the second SSD it was enough to format it as BTRFS then 
#sudo btrfs device add /dev/sdb1 /home -f  (in my case I increased the /home subvol) 
It looks that I achieved my goal like this.

**Comment by classy-giraffe** [comment]
> Related to the second SSD it was enough to format it as BTRFS then #sudo btrfs device add /dev/sdb1 /home -f (in my case I increased the /home subvol) It looks that I achieved my goal like this.

Great, that could help me with adding a multi-device setup to the script.

**Comment by classy-giraffe** [comment]
@pm4rcin Ok i've actually checked that project and yeah it looks promising, let's say that I'll keep my eyes on it and on similar projects (I myself prefer systemd-boot over GRUB, I actually use it on my own system so yeah, I'm keen to switch to it as soon as that project matures.

**Comment by iSparsh** [comment]
IMO We should just go ahead with the systemd script in a `experimental` branch (if possible).

**Comment by classy-giraffe** [comment]
I'm ngl to u guys, systemd-boot support for snapshots is still immature.Im not saying that's not gonna happen, just not anytime soon. 😐
