### ISSUE TITLE
Can't Install arch using it on vbox

### ISSUE THREAD

**Issue by Techlord210** [classy-giraffe/easy-arch#40]
I need help I cant install arch using this script on vbox.
as shown in this video 
https://drive.google.com/file/d/1AfPKQwGtV3jOt6elgWQaxG-3nggX1n0s/view?usp=drivesdk

**Comment by pm4rcin** [comment]
Edit your link so people could see it without asking for permission.

**Comment by Techlord210** [comment]
> Edit your link so people could see it without asking for permission.

Sorry i forgot to do that i have updated it

**Comment by pm4rcin** [comment]
So basically you have to select the number of partition e.g. 1 (not /dev/sdb). I'll make PR to script so it will be more obvious. And also one more thing for you. This script is intended for UEFI installation so you have to change the virtualbox settings. ```Open the VM settings, select System, and on the Motherboard tab, select Enable EFI (special OSes only).``` Or edit that line if you want BIOS installation https://github.com/classy-giraffe/easy-arch/blob/1e11929db1764281e8b418a52fe2691bba446cfb/easy-arch.sh#L361 but I haven't used GRUB for a long time so I could forgot other steps necessary for legacy (BIOS) install.

**Comment by Techlord210** [comment]
> So basically you have to select the number of partition e.g. 1 (not /dev/sdb). I'll make PR to script so it will be more obvious. And also one more thing for you. This script is intended for UEFI installation so you have to change the virtualbox settings. `Open the VM settings, select System, and on the Motherboard tab, select Enable EFI (special OSes only).` Or edit that line if you want BIOS installation
> 
> https://github.com/classy-giraffe/easy-arch/blob/1e11929db1764281e8b418a52fe2691bba446cfb/easy-arch.sh#L361
> 
> but I haven't used GRUB for a long time so I could forgot other steps necessary for legacy (BIOS) install.

didnt worked

**Comment by pm4rcin** [comment]
What exactly didn't work?

**Comment by Techlord210** [comment]
> What exactly didn't work?

After installation system didn't boot `no bootable divice found`
