### ISSUE TITLE
wheel privilege

### ISSUE THREAD

**Issue by OGdmo** [classy-giraffe/easy-arch#42]
On a fresh install using this script, the wheel group is not enabled in the visudo config file.

I didn't now if you chose that behavior but, maybe you can add a line of text saying that:"by default the system don't have the wheel group uncommented from the visudo file, ecc...".

If u won't i can edit maybe the last output text of the script to make the script saying something like that.

best

**Comment by classy-giraffe** [comment]
That can be done for sure (I was actually pretty sure I automated that but apparently I didn't), will be done asap, which means in a couple hours. Thank you so much for making me notice this.

**Comment by classy-giraffe** [comment]
It is fixed now.
