### ISSUE TITLE
Failed to commit transaction conflicting files could not install files to new root

### ISSUE THREAD

**Issue by SpxterWohlf** [classy-giraffe/easy-arch#43]
**Describe the bug**
After choosing my network manager and kernel the script goes on to use pacman to do it's job and fails with the "Failed to commit transaction (conflicting files) could not install files to new root", percedes with the rest of the automation, and throws errors after fstab creation such as could not read grub config, no chpasswd file or directory like packages were never installed, and ends the script. I can chroot in but im unable to install packages as well. 
This is my first time installing arch (switching from kubuntu) and all day ive been unable to follow the Arch Wiki and [this](https://github.com/ejmg/an-idiots-guide-to-installing-arch-on-a-lenovo-carbon-x1-gen-6#disclaimer-sacrifices-incantations-dont-sue-me-etc) to a issue where my machine is unable to even recognize the filesystem like there is no efi (lsblk confirms there is). 

**Additional context**
- Thinkpad X1 Carbon Gen 6 with 512 Gb nvme drive (20KH* model)
- Formatted nvme drive and new partition table
- Turned off secure boot and double checked

**To Reproduce**
1. Run the script
2. Select option 1 for both kernel and network manager
3. Failure to install scripts
4. Setup user and hostname
5. Failure to complete the rest of the system due to missing packages??

**Comment by classy-giraffe** [comment]
Can you boot up Arch Linux live and do a lsblk for me?

**Comment by classy-giraffe** [comment]
I'm gonna close this since it looks like it's inactive, in case you need it, feel free to open a new issue. :D
