### ISSUE TITLE
how to use swap partition instead of ZRAM

### ISSUE THREAD

**Issue by hack3r-0m** [classy-giraffe/easy-arch#44]
what should I replace in the script if I want to use btrfs swap subvolume with swapfile? suspend & hibernate requires swap.

**Comment by classy-giraffe** [comment]
You should create a separate btrfs volume, mount it, put a swapfile on it and then set up grub or whatever bootloader you use to use that file as a resume partition (in GRUB you'd use something like this: `resume=UUID=<uuid of the volume>`.
