### ISSUE TITLE
Selecting Linux Hardened leads to GRUB rescue mode

### ISSUE THREAD

**Issue by aframo** [classy-giraffe/easy-arch#48]
Hello!

Sorry in advance - I have a very Arch-newbie question. (was kind of hoping "easy-arch" would make things easy, heh)
After your script finishes installing, a reboot boots into GRUB, where I assume I'm supposed to be loading the kernel with the `linux` command and initialize other things with `initrd`, but none of the commands I've been finding from google have worked for me. Can you pretty please tell me how to boot into Arch from GRUB?

There's an active discussion on the [Arch subreddit](https://www.reddit.com/r/archlinux/comments/uqvzx1/does_anybody_else_feel_like_the_arch_linux/) about how the official Arch installation guide could be more user friendly. Seeing how your script might be found by other newbies, maybe it would help to add basic instructions for using GRUB into this repo's README? I'm aware this repo isn't exactly aimed at beginners, but helping people get started with BTRFS and ZRAM is probably a good thing.

Hopefully I haven't done something completely wrong.

```
set root=(hd0,gpt1)
linux /vmlinuz-linux
boot
```
Gets me:
```
error: no suitable video mode found.
Booting in blind mode
```
But it doesn't go anywhere from there. I'm guessing I still need to figure out the `initrd` bit.

EDIT:
Just noticed I'm not the only one [not enjoying GRUB](https://github.com/classy-giraffe/easy-arch/issues/31).
Did you give up on rEFInd?

**Comment by classy-giraffe** [comment]
So, technically speaking you should be able to reboot into grub perfectly with no issues and find the arch entry. Are you that didn't happen?

**Comment by classy-giraffe** [comment]
So, technically speaking you should be able to reboot into grub perfectly with no issues and find the arch entry. Are you that didn't happen? Cause you really aren't supposed to start the kernel manually by hand.

**Comment by aframo** [comment]
Thank you for your reply. Not having to start it by hand is a relief and a new problem.
I just realized that if I boot into the SSD (and not GRUB), it boots into GRUB rescue mode with:
```
error: unknown filesystem.
Entering rescue mode...
grub rescue> _
```
Could one of these errors during installation be causing this?
```
warning: directory permissions differ on /mnt/root/
filesystem: 755  package: 750
error: command failed to execute correctly
```

**Comment by aframo** [comment]
I guess the Zen kernel is what I (and most other people) really want, and selecting that works fine too, so this problem is more or less solved for me. Leaving the issue open though, in case someone else has problems with Hardened.

**Comment by classy-giraffe** [comment]
The permission mismatch is an issue but it shouldn't prevent you from booting at all, that's kinda weird. I suppose something went wrong while setting up grub. Do you mind contact me on discord? (@thomas.#9999)

**Comment by classy-giraffe** [comment]
Anyway I just spin up a VM, executed this script selecting the hardened kernel. Everything's working here, could be a you-problem (something related to your hardware). Even in such case, I'd like to help you out, if you don't mind of course. :)

**Comment by aframo** [comment]
Oh, I didn't think it could be hardware related. I'll close the issue then, anyone having problems can see the closed issue too.
I'd be very grateful if you could help me look into it. Sent you a friend request on Discord (I'm Jasper).
