### ISSUE TITLE
Not working on Asus laptop (GL502VS)

### ISSUE THREAD

**Issue by 1rch** [classy-giraffe/easy-arch#50]
Hey! Looking for any help to get this working on my laptop, which seems to be having hardware related complications (or maybe UEFI settings?).

These are the errors that pop up during installation and lead to a non-bootable drive:
```
sed: can't read /mnt/etc/locale.gen: No such file or directory
warning: /mnt/etc/fstab installed as /mnt/etc/fstab.pacnew
warning: /mnt/etc/hosts installed as /mnt/etc/hosts.pacnew
sed: can't read /mnt/etc/default/grub: No such file or directory
useradd: group 'users' does not exist
useradd: the GROUP= configuration in /etc/default/useradd will be ignored
useradd: group 'wheel' does not exist
chpasswd: (user jasper) pam_chauthtok() failed, error:
User not known to the underlying authentication module
chpasswd: (line 1, user jasper) password not changed
sed: can't read /mnt/etc/pacman.conf: No such file or directory

```
I've checked that it's **not** related to:
- Using NVMe or HDD
- Arch version
- Type of kernel
- Type of network adapter

Any ideas? Thank you in advance.

**Comment by DatAres37** [comment]
Same problem for me on a normal desktop PC.
The first error message I get (additionally to those above) is `mount: /mnt/boot: wrong fs type, bad option, bad superblock on /dev/nvme0n1p1, missing codepage or helper program, or other error`

**Comment by classy-giraffe** [comment]
My bad, probably the latest PR fucked up something. I'ma check that tomorrow in a VM. Sorry for the late replies, I'm submerged by school exams. 😐

**Comment by 1rch** [comment]
@classy-giraffe 
Oh sorry, I forgot to mention that I also tried the pre-PR version of easy-arch that had worked on another computer, but doesn't on this laptop. Good luck with the exams!

@DatAres37 
Sorry to hear you're having problems, but I'm glad I'm not the only one. Can you share some of your system specs? It seems we're both running computers with NVMe drives which could give a clue to what's going on. I wonder what else we have in common. 2017ish Asus motherboard?

**Comment by classy-giraffe** [comment]
As far as i know arch has been having issues with some recent nvmes on Intel mobos.. so yeah that's a big clue!

**Comment by 1rch** [comment]
I removed the NVMe drive from the system, but still had all the same errors. Was worth a shot though. If you have any other ideas, I'm all ears.

**Comment by classy-giraffe** [comment]
![image](https://user-images.githubusercontent.com/34209135/174473055-69b0307d-9f26-4761-9e7a-192296274048.png) There's definitely something wrong here.

**Comment by classy-giraffe** [comment]
![image](https://user-images.githubusercontent.com/34209135/174474185-f7a28a17-ccfe-4672-805d-5f4a99b27734.png)
The problem is here.

**Comment by classy-giraffe** [comment]
Could you test the script again?

**Comment by 1rch** [comment]
Thank you for the updates and sorry for the late response.

I'll try the script again in a few days. I've been having some issues with getting Nvidia drivers working on my system.
Something to do with IBT and having to disable it in kernel parameters. Would you happen to know how to do that, or maybe easy-arch already does?

**Comment by classy-giraffe** [comment]
Drivers are very much PC-dependent, I'd need to know your setup. My script doesn't do nothing to kernel parameters btw.
