### ISSUE TITLE
Unbootable installation

### ISSUE THREAD

**Issue by stabilergriller** [classy-giraffe/easy-arch#57]
Script runs through with no problems, but ends up actually in an unbootable state

![PXL_20221009_200246813_1](https://user-images.githubusercontent.com/115423284/194774120-50cb61aa-ac99-41da-ac3b-df075aa3fb7e.jpg)

![Untitled](https://user-images.githubusercontent.com/115423284/194774341-5fc61a40-20d9-4eec-bf39-3ea20fe79986.png)

![Untitled3](https://user-images.githubusercontent.com/115423284/194774499-2c2af06d-95f3-4b15-98c6-10d5d09dc9c2.png)

Switched the boot mode in BIOS from [Legacy+UEFI] to [UEFI], still unbootable. Did the whole installation once more again. Still unbootable.
What now?

![Untitledas](https://user-images.githubusercontent.com/115423284/194774591-d2fbce16-0507-4ed9-9f7b-151c866ebda1.png)

**Comment by classy-giraffe** [comment]
This script was never intended to be used with BIOS system. I made the assumption that everybody uses UEFI these days. With that being said, you could try to switch to UEFI and run the script again (changing it after the installation doesn't work cause the first time you ran it, it probably didn't find the efivars folder and couldn't write to it).

**Comment by classy-giraffe** [comment]
On a sidenote, some UEFI implementations are very buggy. You could try to boot up a UEFI shell and start grub from there.

**Comment by stabilergriller** [comment]
If you have the same issue: A BIOS update for my mainboard fixed it for me.
