### ISSUE TITLE
Make LUKS2 optional

### ISSUE THREAD

**Issue by efwis** [classy-giraffe/easy-arch#62]
This is actually an enhancement request I guess.

It is now adviseable to have a 1G boot partition rather than a 512M.

It would be nice to make the LUKS2 encryption and option. I forked the script to my own github account with the intent of removing the LUKS encryption. For my personal use it is a waste of time to use it.

However,  I'm having a slight issue trying to figure out what I need to do to disable that.

**Comment by classy-giraffe** [comment]
I'll change the EFI size to 1G.

As per your second request, you need to remove all the cryptsetup related stuff, you need to then partition the disk with a single BTRFS partition (and you'll put your volumes there) and disable hooks for encryption in the initramfs.
