### ISSUE TITLE
zsh default shell

### ISSUE THREAD

**Issue by nikitarevenco** [classy-giraffe/easy-arch#64]
It would be neat if zsh was the default shell with easy-arch. What are your thoughts?

**Comment by classy-giraffe** [comment]
I personally use and like Zsh more than bash but the idea is to keep this script as generic as possible (beside some opinionated defaults like the entire BTRFS + LUKS setup). Bash works fine for the majority of people and if you like Zsh you probably know how to install it (feel free to fork this project, add zsh to the list of packages to install and drop a cheeky `chsh -s $(which zsh) $(whoami)` in the script 😄
