### ISSUE TITLE
Consider reducing ESP partition size

### ISSUE THREAD

**Issue by tommytran732** [classy-giraffe/easy-arch#8]
Previously, the script mounts the ESP partition as /boot, and it made sense to have 512MB allocated to it. However, since /boot is now a subvolume and the ESP partition is mounted as /boot/efi (which only contains grubx64.efi), I think its reasonable to reduce it to ~300 MB or even less.

**Comment by classy-giraffe** [comment]
Right, 100 MB should be fine too.

**Comment by tommytran732** [comment]
I see you have already changed it, closing this issue.
